---
- debug:
    msg: "{{ _letsencrypt_certbot_combined_args | pprint }}"

- fail:
    msg: "Expected args to certbot were not as expected"
  when: letsencrypt_test_expected_args != _letsencrypt_certbot_combined_args

- name: acme_le | run a bogus command
  command: certbot-auto --no-self-upgrade invalid-test-arg 2>&1
  ignore_errors: true
  register: _certbot_test_command
  changed_when: false

- set_fact:
    _certbot_test_successful: "{{ certbot_test_success_message in _certbot_test_command.stdout }}"

- fail:
    msg: "Invalid test response from certbot-auto"
  when: not _certbot_test_command
